apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaf-deployment
  labels:
    app: leaf-disease-classification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaf-disease-classification
  template:
    metadata:
      labels:
        app: leaf-disease-classification
    spec:
      containers:
      - name: leaf-disease-classification-container
        # image: docker.io/library/rs-image-v1
        #TODO đổi lại tên image
        image: linhtinh819/leaf-disease-image:v1
        imagePullPolicy: IfNotPresent # must specify
        # command: ["sleep", "infinity"] 
        # resources:
        #   requests:
        #     cpu: "200m" # 100 milliCPU
        #     memory: "100Mi" # 100 Mebibytes
          # limits:
          #   cpu: "150m" # 200 milliCPU
          #   memory: "150Mi" # 200 Mebibytes
        ports:
        - containerPort: 5000
      # imagePullSecrets:
      #   - name: regcred
