apiVersion: v1
kind: Service
metadata:
  name: leaf-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31312
  type: NodePort
  selector:
    app: leaf-disease-classification